version: '3.8'

services:
  ecommerce-app:
    build: ecommerce
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - liquibase
    env_file: .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

  postgres:
    image: postgres:latest
    env_file: .env
    environment:
      POSTGRES_DB:  ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    restart: always

  liquibase:
    image: liquibase/liquibase:latest
    volumes:
      - ./src/main/resources/db/changelog:/liquibase/changelog
    command: update
    env_file: .env
    environment:
      - DATABASE_URL=jdbc:jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      - DATABASE_USERNAME=${DB_USERNAME}
      - DATABASE_PASSWORD=${DB_PASSWORD}
    depends_on:
      - postgres
