version: '3.8'

services:
  ecommerce-app:
    build: ecommerce
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - liquibase
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ecommerce_v2
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1111

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ecommerce_v2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
    ports:
      - "5432:5432"
    restart: always

  liquibase:
    image: liquibase/liquibase:latest
    volumes:
      - ./src/main/resources/db/changelog:/liquibase/changelog
    command: update
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/ecommerce_v2
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=1111
    depends_on:
      - postgres
