networks:
  ecommerce_network:
    driver: bridge

services:
  ecommerce-app:
    build: .
    ports:
      - "8082:8082"
    container_name: ecommerce-app
    depends_on:
      - ecommerce_postgres_db
      - ecommerce_liquibase_changesets
    env_file: .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST_DOCKER}:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    networks:
      - ecommerce_network
    restart: always


  ecommerce_postgres_db:
    image: postgres:alpine
    container_name: ecommerce_postgres_db
    env_file: .env
    environment:
      POSTGRES_DB:  ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ecommerce_network
    restart: always

  ecommerce_liquibase_changesets:
    image: liquibase/liquibase:latest
    container_name: ecommerce_liquibase_changesets
    volumes:
      - ./src/main/resources/db/changelog/db.changelog-master.yaml:/liquibase/db/changelog/db.changelog-master.yaml
    networks:
      - ecommerce_network
    command: --changelog-file=/liquibase/db/changelog/db.changelog-master.yaml
    env_file: .env
    environment:
      - LIQUIBASE_COMMAND_URL=jdbc:postgresql://${DB_HOST_DOCKER}:${DB_PORT}/${DB_NAME}
      - LIQUIBASE_COMMAND_USERNAME=${DB_USERNAME}
      - LIQUIBASE_COMMAND_PASSWORD=${DB_PASSWORD}
    depends_on:
      - ecommerce_postgres_db

volumes:
  pgdata:
