spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_v2
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1111

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none





