spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml

logging:
  level:
    liquibase: DEBUG
    root: DEBUG

server:
  port: 8082





