spring:
  profiles:
    active: ${SPRING_PROFILE:local}

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml

logging:
  level:
    liquibase: DEBUG

server:
  port: 8082





