spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_v2
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1111

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml

#  session:
#    jdbc:
#      initialize-schema: always
#    store-type: jdbc

  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Ov23liAk8lAQ72P1nHcj
            clientSecret: c8c6f8e82b6d9efb9ec06452dea94e29b97fc072
            scope: read:user, user:email
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id

logging:
  level:
    org:
      springframework:
        security: DEBUG
    liquibase: DEBUG

server:
  port: 8080





